### ISSUE TITLE
Que es esto


### ISSUE THREAD

**Issue by Paulino94** [joseluisgs/AccesoDatos-02-2022-2023#1]
https://docs.google.com/presentation/d/e/2PACX-1vREGaz7tpUv-5aBTSik-upEP-16c1Gbo7nxEAX1Wszb7hJRbKT9IAazL-jVBVMJqBGrkVU0jxsvQQsk/pub?start=false&loop=false&delayms=3000#LLIVSZUBWXN

**Comment by joseluisgs** [comment]
No sé a lo que te refieres. Ni esa es una presentación mía, por favor usa este repositorio y los issues para referirte a materiales que se encuentra aquí
